# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Osengine_config = debug

else ifeq ($(config),release)
  Osengine_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Osengine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Osengine:
ifneq (,$(Osengine_config))
	@echo "==== Building Osengine ($(Osengine_config)) ===="
	@${MAKE} --no-print-directory -C . -f Osengine.make config=$(Osengine_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Osengine.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Osengine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"