# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -Iinclude -Idependencies/llvm/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS += -lLLVM-20 -lpthread -lquadmath -lucrt -lmsvcrt
LDDEPS +=
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug-windows-x86_64
TARGET = $(TARGETDIR)/Osengine.exe
OBJDIR = bin-int/Debug-windows-x86_64
DEFINES += -DDEBUG -DPLATFORM_WINDOWS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g -mno-stack-arg-probe
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g -std=c++23 -mno-stack-arg-probe
ALL_LDFLAGS += $(LDFLAGS) -Ldependencies/llvm/lib -L/usr/lib64 -m64
define POSTBUILDCMDS
	@echo Running postbuild commands
	powershell -Command "if (-not (Test-Path -Path 'bin/Debug-windows-x86_64')) { New-Item -ItemType Directory -Force -Path 'bin/Debug-windows-x86_64' }"
	powershell -Command "Copy-Item 'dependencies/llvm/bin/*.dll' -Destination 'bin/Debug-windows-x86_64'"
endef

else ifeq ($(config),release)
TARGETDIR = bin/Release-windows-x86_64
TARGET = $(TARGETDIR)/Osengine.exe
OBJDIR = bin-int/Release-windows-x86_64
DEFINES += -DNDEBUG -DPLATFORM_WINDOWS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -mno-stack-arg-probe
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++23 -mno-stack-arg-probe
ALL_LDFLAGS += $(LDFLAGS) -Ldependencies/llvm/lib -L/usr/lib64 -m64 -s
define POSTBUILDCMDS
	@echo Running postbuild commands
	powershell -Command "if (-not (Test-Path -Path 'bin/Release-windows-x86_64')) { New-Item -ItemType Directory -Force -Path 'bin/Release-windows-x86_64' }"
	powershell -Command "Copy-Item 'dependencies/llvm/bin/*.dll' -Destination 'bin/Release-windows-x86_64'"
endef

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/AccessStatements.o
GENERATED += $(OBJDIR)/AndriodLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/Application.o
GENERATED += $(OBJDIR)/ArrowAccessStatement.o
GENERATED += $(OBJDIR)/AssignmentsAndGetterStatements.o
GENERATED += $(OBJDIR)/BaseType.o
GENERATED += $(OBJDIR)/CLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/CallStatement.o
GENERATED += $(OBJDIR)/Casting.o
GENERATED += $(OBJDIR)/Compiler.o
GENERATED += $(OBJDIR)/Console.o
GENERATED += $(OBJDIR)/ControlFlowStatements.o
GENERATED += $(OBJDIR)/Core.o
GENERATED += $(OBJDIR)/DarwninLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/DerivedTypes.o
GENERATED += $(OBJDIR)/DynamicLibraryLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/Engine.o
GENERATED += $(OBJDIR)/EngineConfigs.o
GENERATED += $(OBJDIR)/EntityStatements.o
GENERATED += $(OBJDIR)/ExpressionStatements.o
GENERATED += $(OBJDIR)/FileSpan.o
GENERATED += $(OBJDIR)/FunctionDeclaration.o
GENERATED += $(OBJDIR)/IRGenAssignmentsAndGetters.o
GENERATED += $(OBJDIR)/IRGenControlFlow.o
GENERATED += $(OBJDIR)/IRGenFunctions.o
GENERATED += $(OBJDIR)/IRGenLiterals.o
GENERATED += $(OBJDIR)/IRGenerator.o
GENERATED += $(OBJDIR)/IRGeneratorAccess.o
GENERATED += $(OBJDIR)/IRGeneratorCodegen.o
GENERATED += $(OBJDIR)/IRGeneratorDebuggingHelpers.o
GENERATED += $(OBJDIR)/IRGeneratorEntities.o
GENERATED += $(OBJDIR)/IRGeneratorExpressions.o
GENERATED += $(OBJDIR)/IRGeneratorInitializersAndFinalizers.o
GENERATED += $(OBJDIR)/IRGeneratorModules.o
GENERATED += $(OBJDIR)/IRGeneratorObjects.o
GENERATED += $(OBJDIR)/IRGeneratorOptimizers.o
GENERATED += $(OBJDIR)/IRGeneratorOptionalHelpers.o
GENERATED += $(OBJDIR)/IRGeneratorTargetHelpers.o
GENERATED += $(OBJDIR)/IRGeneratorTypes.o
GENERATED += $(OBJDIR)/IndexAccessStatment.o
GENERATED += $(OBJDIR)/JITBackend.o
GENERATED += $(OBJDIR)/LLVMAOTBackend.o
GENERATED += $(OBJDIR)/LLVMExternalFunctionResolver.o
GENERATED += $(OBJDIR)/LLVMJITBackend.o
GENERATED += $(OBJDIR)/LexLiterals.o
GENERATED += $(OBJDIR)/LexNumbers.o
GENERATED += $(OBJDIR)/LexOperators.o
GENERATED += $(OBJDIR)/LexStrings.o
GENERATED += $(OBJDIR)/Lexer.o
GENERATED += $(OBJDIR)/LinuxLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/LiteralStatements.o
GENERATED += $(OBJDIR)/MemberAccessStatement.o
GENERATED += $(OBJDIR)/ModuleAndImportStatements.o
GENERATED += $(OBJDIR)/ParseAssignments.o
GENERATED += $(OBJDIR)/ParseBlock.o
GENERATED += $(OBJDIR)/ParseControlFlow.o
GENERATED += $(OBJDIR)/ParseEntities.o
GENERATED += $(OBJDIR)/ParseExpression.o
GENERATED += $(OBJDIR)/ParseFunctions.o
GENERATED += $(OBJDIR)/ParseHelpers.o
GENERATED += $(OBJDIR)/ParseIdentifiers.o
GENERATED += $(OBJDIR)/ParseModulesAndImports.o
GENERATED += $(OBJDIR)/ParseObjects.o
GENERATED += $(OBJDIR)/ParseStatements.o
GENERATED += $(OBJDIR)/ParseStrings.o
GENERATED += $(OBJDIR)/ParseTypes.o
GENERATED += $(OBJDIR)/Parser.o
GENERATED += $(OBJDIR)/PosixLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/PrototypeStatements.o
GENERATED += $(OBJDIR)/SmartPlatformLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/Statement.o
GENERATED += $(OBJDIR)/StaticLibraryLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/SymbolTable.o
GENERATED += $(OBJDIR)/Target_config.o
GENERATED += $(OBJDIR)/Tokens.o
GENERATED += $(OBJDIR)/TraitCapability.o
GENERATED += $(OBJDIR)/TypeKind.o
GENERATED += $(OBJDIR)/TypeStatements.o
GENERATED += $(OBJDIR)/Types.o
GENERATED += $(OBJDIR)/WebAssemblyLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/WindowsApiLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/main.o
GENERATED += $(OBJDIR)/utils.o
OBJECTS += $(OBJDIR)/AccessStatements.o
OBJECTS += $(OBJDIR)/AndriodLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/Application.o
OBJECTS += $(OBJDIR)/ArrowAccessStatement.o
OBJECTS += $(OBJDIR)/AssignmentsAndGetterStatements.o
OBJECTS += $(OBJDIR)/BaseType.o
OBJECTS += $(OBJDIR)/CLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/CallStatement.o
OBJECTS += $(OBJDIR)/Casting.o
OBJECTS += $(OBJDIR)/Compiler.o
OBJECTS += $(OBJDIR)/Console.o
OBJECTS += $(OBJDIR)/ControlFlowStatements.o
OBJECTS += $(OBJDIR)/Core.o
OBJECTS += $(OBJDIR)/DarwninLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/DerivedTypes.o
OBJECTS += $(OBJDIR)/DynamicLibraryLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/Engine.o
OBJECTS += $(OBJDIR)/EngineConfigs.o
OBJECTS += $(OBJDIR)/EntityStatements.o
OBJECTS += $(OBJDIR)/ExpressionStatements.o
OBJECTS += $(OBJDIR)/FileSpan.o
OBJECTS += $(OBJDIR)/FunctionDeclaration.o
OBJECTS += $(OBJDIR)/IRGenAssignmentsAndGetters.o
OBJECTS += $(OBJDIR)/IRGenControlFlow.o
OBJECTS += $(OBJDIR)/IRGenFunctions.o
OBJECTS += $(OBJDIR)/IRGenLiterals.o
OBJECTS += $(OBJDIR)/IRGenerator.o
OBJECTS += $(OBJDIR)/IRGeneratorAccess.o
OBJECTS += $(OBJDIR)/IRGeneratorCodegen.o
OBJECTS += $(OBJDIR)/IRGeneratorDebuggingHelpers.o
OBJECTS += $(OBJDIR)/IRGeneratorEntities.o
OBJECTS += $(OBJDIR)/IRGeneratorExpressions.o
OBJECTS += $(OBJDIR)/IRGeneratorInitializersAndFinalizers.o
OBJECTS += $(OBJDIR)/IRGeneratorModules.o
OBJECTS += $(OBJDIR)/IRGeneratorObjects.o
OBJECTS += $(OBJDIR)/IRGeneratorOptimizers.o
OBJECTS += $(OBJDIR)/IRGeneratorOptionalHelpers.o
OBJECTS += $(OBJDIR)/IRGeneratorTargetHelpers.o
OBJECTS += $(OBJDIR)/IRGeneratorTypes.o
OBJECTS += $(OBJDIR)/IndexAccessStatment.o
OBJECTS += $(OBJDIR)/JITBackend.o
OBJECTS += $(OBJDIR)/LLVMAOTBackend.o
OBJECTS += $(OBJDIR)/LLVMExternalFunctionResolver.o
OBJECTS += $(OBJDIR)/LLVMJITBackend.o
OBJECTS += $(OBJDIR)/LexLiterals.o
OBJECTS += $(OBJDIR)/LexNumbers.o
OBJECTS += $(OBJDIR)/LexOperators.o
OBJECTS += $(OBJDIR)/LexStrings.o
OBJECTS += $(OBJDIR)/Lexer.o
OBJECTS += $(OBJDIR)/LinuxLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/LiteralStatements.o
OBJECTS += $(OBJDIR)/MemberAccessStatement.o
OBJECTS += $(OBJDIR)/ModuleAndImportStatements.o
OBJECTS += $(OBJDIR)/ParseAssignments.o
OBJECTS += $(OBJDIR)/ParseBlock.o
OBJECTS += $(OBJDIR)/ParseControlFlow.o
OBJECTS += $(OBJDIR)/ParseEntities.o
OBJECTS += $(OBJDIR)/ParseExpression.o
OBJECTS += $(OBJDIR)/ParseFunctions.o
OBJECTS += $(OBJDIR)/ParseHelpers.o
OBJECTS += $(OBJDIR)/ParseIdentifiers.o
OBJECTS += $(OBJDIR)/ParseModulesAndImports.o
OBJECTS += $(OBJDIR)/ParseObjects.o
OBJECTS += $(OBJDIR)/ParseStatements.o
OBJECTS += $(OBJDIR)/ParseStrings.o
OBJECTS += $(OBJDIR)/ParseTypes.o
OBJECTS += $(OBJDIR)/Parser.o
OBJECTS += $(OBJDIR)/PosixLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/PrototypeStatements.o
OBJECTS += $(OBJDIR)/SmartPlatformLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/Statement.o
OBJECTS += $(OBJDIR)/StaticLibraryLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/SymbolTable.o
OBJECTS += $(OBJDIR)/Target_config.o
OBJECTS += $(OBJDIR)/Tokens.o
OBJECTS += $(OBJDIR)/TraitCapability.o
OBJECTS += $(OBJDIR)/TypeKind.o
OBJECTS += $(OBJDIR)/TypeStatements.o
OBJECTS += $(OBJDIR)/Types.o
OBJECTS += $(OBJDIR)/WebAssemblyLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/WindowsApiLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/utils.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking Osengine
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Osengine
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/Application.o: src/Application.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/JITBackend.o: src/Backends/JITBackend.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGenerator.o: src/Backends/llvm/IRGenerator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AndriodLLVMFunctionResolver.o: src/Backends/llvm/IRGenerator/ExternalFunctionResolvers/AndriodLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CLLVMFunctionResolver.o: src/Backends/llvm/IRGenerator/ExternalFunctionResolvers/CLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DarwninLLVMFunctionResolver.o: src/Backends/llvm/IRGenerator/ExternalFunctionResolvers/DarwninLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DynamicLibraryLLVMFunctionResolver.o: src/Backends/llvm/IRGenerator/ExternalFunctionResolvers/DynamicLibraryLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LinuxLLVMFunctionResolver.o: src/Backends/llvm/IRGenerator/ExternalFunctionResolvers/LinuxLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PosixLLVMFunctionResolver.o: src/Backends/llvm/IRGenerator/ExternalFunctionResolvers/PosixLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SmartPlatformLLVMFunctionResolver.o: src/Backends/llvm/IRGenerator/ExternalFunctionResolvers/SmartPlatformLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StaticLibraryLLVMFunctionResolver.o: src/Backends/llvm/IRGenerator/ExternalFunctionResolvers/StaticLibraryLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WebAssemblyLLVMFunctionResolver.o: src/Backends/llvm/IRGenerator/ExternalFunctionResolvers/WebAssemblyLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WindowsApiLLVMFunctionResolver.o: src/Backends/llvm/IRGenerator/ExternalFunctionResolvers/WindowsApiLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGenAssignmentsAndGetters.o: src/Backends/llvm/IRGenerator/IRGenAssignmentsAndGetters.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGenControlFlow.o: src/Backends/llvm/IRGenerator/IRGenControlFlow.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGenFunctions.o: src/Backends/llvm/IRGenerator/IRGenFunctions.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGenLiterals.o: src/Backends/llvm/IRGenerator/IRGenLiterals.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorAccess.o: src/Backends/llvm/IRGenerator/IRGeneratorAccess.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorCodegen.o: src/Backends/llvm/IRGenerator/IRGeneratorCodegen.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorDebuggingHelpers.o: src/Backends/llvm/IRGenerator/IRGeneratorDebuggingHelpers.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorEntities.o: src/Backends/llvm/IRGenerator/IRGeneratorEntities.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorExpressions.o: src/Backends/llvm/IRGenerator/IRGeneratorExpressions.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorInitializersAndFinalizers.o: src/Backends/llvm/IRGenerator/IRGeneratorInitializersAndFinalizers.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorModules.o: src/Backends/llvm/IRGenerator/IRGeneratorModules.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorObjects.o: src/Backends/llvm/IRGenerator/IRGeneratorObjects.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorOptimizers.o: src/Backends/llvm/IRGenerator/IRGeneratorOptimizers.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorOptionalHelpers.o: src/Backends/llvm/IRGenerator/IRGeneratorOptionalHelpers.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorTargetHelpers.o: src/Backends/llvm/IRGenerator/IRGeneratorTargetHelpers.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorTypes.o: src/Backends/llvm/IRGenerator/IRGeneratorTypes.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LLVMAOTBackend.o: src/Backends/llvm/LLVMAOTBackend.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LLVMExternalFunctionResolver.o: src/Backends/llvm/LLVMExternalFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LLVMJITBackend.o: src/Backends/llvm/LLVMJITBackend.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Compiler.o: src/Compiler.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Console.o: src/Console.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Core.o: src/Core.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Engine.o: src/Engine.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EngineConfigs.o: src/EngineConfigs.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FileSpan.o: src/FileSpan.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LexLiterals.o: src/Lexer/LexLiterals.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LexNumbers.o: src/Lexer/LexNumbers.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LexOperators.o: src/Lexer/LexOperators.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LexStrings.o: src/Lexer/LexStrings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Lexer.o: src/Lexer/Lexer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseAssignments.o: src/Parser/ParseAssignments.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseBlock.o: src/Parser/ParseBlock.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseControlFlow.o: src/Parser/ParseControlFlow.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseEntities.o: src/Parser/ParseEntities.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseExpression.o: src/Parser/ParseExpression.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseFunctions.o: src/Parser/ParseFunctions.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseHelpers.o: src/Parser/ParseHelpers.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseIdentifiers.o: src/Parser/ParseIdentifiers.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseModulesAndImports.o: src/Parser/ParseModulesAndImports.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseObjects.o: src/Parser/ParseObjects.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseStatements.o: src/Parser/ParseStatements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseStrings.o: src/Parser/ParseStrings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParseTypes.o: src/Parser/ParseTypes.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Parser.o: src/Parser/Parser.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AccessStatements.o: src/Statements/AccessStatements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ArrowAccessStatement.o: src/Statements/ArrowAccessStatement.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AssignmentsAndGetterStatements.o: src/Statements/AssignmentsAndGetterStatements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CallStatement.o: src/Statements/CallStatement.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ControlFlowStatements.o: src/Statements/ControlFlowStatements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EntityStatements.o: src/Statements/EntityStatements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ExpressionStatements.o: src/Statements/ExpressionStatements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FunctionDeclaration.o: src/Statements/FunctionDeclaration.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IndexAccessStatment.o: src/Statements/IndexAccessStatment.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LiteralStatements.o: src/Statements/LiteralStatements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MemberAccessStatement.o: src/Statements/MemberAccessStatement.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ModuleAndImportStatements.o: src/Statements/ModuleAndImportStatements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PrototypeStatements.o: src/Statements/PrototypeStatements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Statement.o: src/Statements/Statement.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TypeStatements.o: src/Statements/TypeStatements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SymbolTable.o: src/SymbolTable.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Target_config.o: src/Target_config.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Tokens.o: src/Tokens.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BaseType.o: src/Types/BaseType.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Casting.o: src/Types/Casting.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DerivedTypes.o: src/Types/DerivedTypes.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TraitCapability.o: src/Types/TraitCapability.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TypeKind.o: src/Types/TypeKind.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Types.o: src/Types/Types.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main.o: src/main.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utils.o: src/utils.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif