# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -Iinclude -Idependencies/llvm/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -mno-stack-arg-probe
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -std=c++23 -mno-stack-arg-probe
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS += -lLLVM-20 -lpthread -lquadmath -lucrt -lmsvcrt
LDDEPS +=
ALL_LDFLAGS += $(LDFLAGS) -Ldependencies/llvm/lib -L/usr/lib64 -m64 -s
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug-windows-x86_64
TARGET = $(TARGETDIR)/Osengine.exe
OBJDIR = bin-int/Debug-windows-x86_64
DEFINES += -DDEBUG -DPLATFORM_WINDOWS
define POSTBUILDCMDS
	@echo Running postbuild commands
	powershell -Command "if (-not (Test-Path -Path 'bin/Debug-windows-x86_64')) { New-Item -ItemType Directory -Force -Path 'bin/Debug-windows-x86_64' }"
	powershell -Command "Copy-Item 'dependencies/llvm/bin/*.dll' -Destination 'bin/Debug-windows-x86_64'"
endef

else ifeq ($(config),release)
TARGETDIR = bin/Release-windows-x86_64
TARGET = $(TARGETDIR)/Osengine.exe
OBJDIR = bin-int/Release-windows-x86_64
DEFINES += -DNDEBUG -DPLATFORM_WINDOWS
define POSTBUILDCMDS
	@echo Running postbuild commands
	powershell -Command "if (-not (Test-Path -Path 'bin/Release-windows-x86_64')) { New-Item -ItemType Directory -Force -Path 'bin/Release-windows-x86_64' }"
	powershell -Command "Copy-Item 'dependencies/llvm/bin/*.dll' -Destination 'bin/Release-windows-x86_64'"
endef

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/Access.o
GENERATED += $(OBJDIR)/AndriodLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/Assignments.o
GENERATED += $(OBJDIR)/AssignmentsAndGetters.o
GENERATED += $(OBJDIR)/Block.o
GENERATED += $(OBJDIR)/CLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/ControlFlow.o
GENERATED += $(OBJDIR)/ControlFlow1.o
GENERATED += $(OBJDIR)/Core.o
GENERATED += $(OBJDIR)/DarwninLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/DynamicLibraryLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/EngineConfigs.o
GENERATED += $(OBJDIR)/Entities.o
GENERATED += $(OBJDIR)/Entities1.o
GENERATED += $(OBJDIR)/Expression.o
GENERATED += $(OBJDIR)/Expression1.o
GENERATED += $(OBJDIR)/Expressions.o
GENERATED += $(OBJDIR)/Functions.o
GENERATED += $(OBJDIR)/Helpers.o
GENERATED += $(OBJDIR)/IRGenAssignmentsAndGetters.o
GENERATED += $(OBJDIR)/IRGenControlFlow.o
GENERATED += $(OBJDIR)/IRGenFunctions.o
GENERATED += $(OBJDIR)/IRGenLiterals.o
GENERATED += $(OBJDIR)/IRGenerator.o
GENERATED += $(OBJDIR)/IRGeneratorAccess.o
GENERATED += $(OBJDIR)/IRGeneratorDebuggingHelpers.o
GENERATED += $(OBJDIR)/IRGeneratorEntities.o
GENERATED += $(OBJDIR)/IRGeneratorExpressions.o
GENERATED += $(OBJDIR)/IRGeneratorModules.o
GENERATED += $(OBJDIR)/IRGeneratorObjects.o
GENERATED += $(OBJDIR)/IRGeneratorTypes.o
GENERATED += $(OBJDIR)/Identifiers.o
GENERATED += $(OBJDIR)/JITBackend.o
GENERATED += $(OBJDIR)/JITCompiler.o
GENERATED += $(OBJDIR)/LLVMAOTBackend.o
GENERATED += $(OBJDIR)/LLVMExternalFunctionResolver.o
GENERATED += $(OBJDIR)/LLVMJITBackend.o
GENERATED += $(OBJDIR)/Lexer.o
GENERATED += $(OBJDIR)/LinuxLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/Literals.o
GENERATED += $(OBJDIR)/ModulesAndImports.o
GENERATED += $(OBJDIR)/ModulesAndImports1.o
GENERATED += $(OBJDIR)/Objects.o
GENERATED += $(OBJDIR)/Parser.o
GENERATED += $(OBJDIR)/PosixLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/Prototypes.o
GENERATED += $(OBJDIR)/SmartPlatformLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/Statement.o
GENERATED += $(OBJDIR)/Statements.o
GENERATED += $(OBJDIR)/StaticLibraryLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/String.o
GENERATED += $(OBJDIR)/Tokens.o
GENERATED += $(OBJDIR)/Types.o
GENERATED += $(OBJDIR)/WebAssemblyLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/WindowsApiLLVMFunctionResolver.o
GENERATED += $(OBJDIR)/main.o
GENERATED += $(OBJDIR)/utils.o
OBJECTS += $(OBJDIR)/Access.o
OBJECTS += $(OBJDIR)/AndriodLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/Assignments.o
OBJECTS += $(OBJDIR)/AssignmentsAndGetters.o
OBJECTS += $(OBJDIR)/Block.o
OBJECTS += $(OBJDIR)/CLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/ControlFlow.o
OBJECTS += $(OBJDIR)/ControlFlow1.o
OBJECTS += $(OBJDIR)/Core.o
OBJECTS += $(OBJDIR)/DarwninLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/DynamicLibraryLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/EngineConfigs.o
OBJECTS += $(OBJDIR)/Entities.o
OBJECTS += $(OBJDIR)/Entities1.o
OBJECTS += $(OBJDIR)/Expression.o
OBJECTS += $(OBJDIR)/Expression1.o
OBJECTS += $(OBJDIR)/Expressions.o
OBJECTS += $(OBJDIR)/Functions.o
OBJECTS += $(OBJDIR)/Helpers.o
OBJECTS += $(OBJDIR)/IRGenAssignmentsAndGetters.o
OBJECTS += $(OBJDIR)/IRGenControlFlow.o
OBJECTS += $(OBJDIR)/IRGenFunctions.o
OBJECTS += $(OBJDIR)/IRGenLiterals.o
OBJECTS += $(OBJDIR)/IRGenerator.o
OBJECTS += $(OBJDIR)/IRGeneratorAccess.o
OBJECTS += $(OBJDIR)/IRGeneratorDebuggingHelpers.o
OBJECTS += $(OBJDIR)/IRGeneratorEntities.o
OBJECTS += $(OBJDIR)/IRGeneratorExpressions.o
OBJECTS += $(OBJDIR)/IRGeneratorModules.o
OBJECTS += $(OBJDIR)/IRGeneratorObjects.o
OBJECTS += $(OBJDIR)/IRGeneratorTypes.o
OBJECTS += $(OBJDIR)/Identifiers.o
OBJECTS += $(OBJDIR)/JITBackend.o
OBJECTS += $(OBJDIR)/JITCompiler.o
OBJECTS += $(OBJDIR)/LLVMAOTBackend.o
OBJECTS += $(OBJDIR)/LLVMExternalFunctionResolver.o
OBJECTS += $(OBJDIR)/LLVMJITBackend.o
OBJECTS += $(OBJDIR)/Lexer.o
OBJECTS += $(OBJDIR)/LinuxLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/Literals.o
OBJECTS += $(OBJDIR)/ModulesAndImports.o
OBJECTS += $(OBJDIR)/ModulesAndImports1.o
OBJECTS += $(OBJDIR)/Objects.o
OBJECTS += $(OBJDIR)/Parser.o
OBJECTS += $(OBJDIR)/PosixLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/Prototypes.o
OBJECTS += $(OBJDIR)/SmartPlatformLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/Statement.o
OBJECTS += $(OBJDIR)/Statements.o
OBJECTS += $(OBJDIR)/StaticLibraryLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/String.o
OBJECTS += $(OBJDIR)/Tokens.o
OBJECTS += $(OBJDIR)/Types.o
OBJECTS += $(OBJDIR)/WebAssemblyLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/WindowsApiLLVMFunctionResolver.o
OBJECTS += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/utils.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking Osengine
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Osengine
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/Core.o: src/Core.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Expression.o: src/Core/Expression.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Types.o: src/Core/Types.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/JITBackend.o: src/engine/Backends/JITBackend.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AndriodLLVMFunctionResolver.o: src/engine/Backends/llvm/ExternalFunctionResolvers/AndriodLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CLLVMFunctionResolver.o: src/engine/Backends/llvm/ExternalFunctionResolvers/CLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DarwninLLVMFunctionResolver.o: src/engine/Backends/llvm/ExternalFunctionResolvers/DarwninLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DynamicLibraryLLVMFunctionResolver.o: src/engine/Backends/llvm/ExternalFunctionResolvers/DynamicLibraryLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LinuxLLVMFunctionResolver.o: src/engine/Backends/llvm/ExternalFunctionResolvers/LinuxLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PosixLLVMFunctionResolver.o: src/engine/Backends/llvm/ExternalFunctionResolvers/PosixLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SmartPlatformLLVMFunctionResolver.o: src/engine/Backends/llvm/ExternalFunctionResolvers/SmartPlatformLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StaticLibraryLLVMFunctionResolver.o: src/engine/Backends/llvm/ExternalFunctionResolvers/StaticLibraryLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WebAssemblyLLVMFunctionResolver.o: src/engine/Backends/llvm/ExternalFunctionResolvers/WebAssemblyLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WindowsApiLLVMFunctionResolver.o: src/engine/Backends/llvm/ExternalFunctionResolvers/WindowsApiLLVMFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGenAssignmentsAndGetters.o: src/engine/Backends/llvm/IRGenAssignmentsAndGetters.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGenControlFlow.o: src/engine/Backends/llvm/IRGenControlFlow.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGenFunctions.o: src/engine/Backends/llvm/IRGenFunctions.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGenLiterals.o: src/engine/Backends/llvm/IRGenLiterals.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGenerator.o: src/engine/Backends/llvm/IRGenerator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorAccess.o: src/engine/Backends/llvm/IRGeneratorAccess.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorDebuggingHelpers.o: src/engine/Backends/llvm/IRGeneratorDebuggingHelpers.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorEntities.o: src/engine/Backends/llvm/IRGeneratorEntities.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorExpressions.o: src/engine/Backends/llvm/IRGeneratorExpressions.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorModules.o: src/engine/Backends/llvm/IRGeneratorModules.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorObjects.o: src/engine/Backends/llvm/IRGeneratorObjects.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IRGeneratorTypes.o: src/engine/Backends/llvm/IRGeneratorTypes.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LLVMAOTBackend.o: src/engine/Backends/llvm/LLVMAOTBackend.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LLVMExternalFunctionResolver.o: src/engine/Backends/llvm/LLVMExternalFunctionResolver.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LLVMJITBackend.o: src/engine/Backends/llvm/LLVMJITBackend.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EngineConfigs.o: src/engine/EngineConfigs.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/JITCompiler.o: src/engine/JITCompiler.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Lexer.o: src/engine/Lexer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Assignments.o: src/engine/Parser/Assignments.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Block.o: src/engine/Parser/Block.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ControlFlow.o: src/engine/Parser/ControlFlow.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Entities.o: src/engine/Parser/Entities.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Expression1.o: src/engine/Parser/Expression.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Functions.o: src/engine/Parser/Functions.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Helpers.o: src/engine/Parser/Helpers.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Identifiers.o: src/engine/Parser/Identifiers.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ModulesAndImports.o: src/engine/Parser/ModulesAndImports.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Objects.o: src/engine/Parser/Objects.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Parser.o: src/engine/Parser/Parser.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Statements.o: src/engine/Parser/Statements.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/String.o: src/engine/Parser/String.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Access.o: src/engine/Statements/Access.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AssignmentsAndGetters.o: src/engine/Statements/AssignmentsAndGetters.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ControlFlow1.o: src/engine/Statements/ControlFlow.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Entities1.o: src/engine/Statements/Entities.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Expressions.o: src/engine/Statements/Expressions.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Literals.o: src/engine/Statements/Literals.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ModulesAndImports1.o: src/engine/Statements/ModulesAndImports.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Prototypes.o: src/engine/Statements/Prototypes.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Statement.o: src/engine/Statements/Statement.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Tokens.o: src/engine/Tokens.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main.o: src/main.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utils.o: src/utils.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif